source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# Views candy
gem 'jquery-rails'
gem 'will_paginate'
#gem 'haml'
#group :development do
#  gem 'hpricot'
#  gem 'ruby_parser'
#  gem 'aruba'
#  gem 'haml-rails'
#  gem 'web-app-theme'
#end

# Authentication and user Abilities
gem 'devise'
gem 'cancan'

# Specification and testing
gem 'rspec', :group => [:development, :test]
gem 'rspec-rails', :group => [:development, :test]

# Testing
group :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'capybara-webkit'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'ruby-debug19', :require => 'ruby-debug', :group => :development
