
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package javadb.timely;
import javadb.timely.database_1.IDatabase1;

import java.io.Serializable;

public interface IDatabases extends Serializable {
  public IDatabase1 getDatabase1();
}
