
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package javadb.timely.database_1;

import java.io.IOException;
import java.sql.SQLException;

import com.rapleaf.jack.DbFixtures;
import javadb.timely.DatabasesImpl;
import javadb.timely.IDatabases;

public class BaseDatabase1Fixtures extends DbFixtures {

  public static void setup() throws SQLException, IOException {
    setup(new DatabasesImpl());
  }

  public static void setup(IDatabases databases) throws SQLException, IOException {
    databases.getDatabase1().accessories().deleteAll();
    databases.getDatabase1().events().deleteAll();
    databases.getDatabase1().eventsRooms().deleteAll();
    databases.getDatabase1().groups().deleteAll();
    databases.getDatabase1().groupsPeople().deleteAll();
    databases.getDatabase1().people().deleteAll();
    databases.getDatabase1().rooms().deleteAll();
    databases.getDatabase1().schoolTerms().deleteAll();
    databases.getDatabase1().subjects().deleteAll();
    databases.getDatabase1().termSettings().deleteAll();
    databases.getDatabase1().userSettings().deleteAll();
  }
}
