
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package javadb.timely.database_1;

import com.rapleaf.jack.IDb;
import javadb.timely.database_1.iface.IAccessoryPersistence;
import javadb.timely.database_1.iface.IEventPersistence;
import javadb.timely.database_1.iface.IEventsRoomPersistence;
import javadb.timely.database_1.iface.IGroupPersistence;
import javadb.timely.database_1.iface.IGroupsPersonPersistence;
import javadb.timely.database_1.iface.IPersonPersistence;
import javadb.timely.database_1.iface.IRoomPersistence;
import javadb.timely.database_1.iface.ISchoolTermPersistence;
import javadb.timely.database_1.iface.ISubjectPersistence;
import javadb.timely.database_1.iface.ITermSettingPersistence;
import javadb.timely.database_1.iface.IUserSettingPersistence;

public interface IDatabase1 extends IDb {
  public IAccessoryPersistence accessories();
  public IEventPersistence events();
  public IEventsRoomPersistence eventsRooms();
  public IGroupPersistence groups();
  public IGroupsPersonPersistence groupsPeople();
  public IPersonPersistence people();
  public IRoomPersistence rooms();
  public ISchoolTermPersistence schoolTerms();
  public ISubjectPersistence subjects();
  public ITermSettingPersistence termSettings();
  public IUserSettingPersistence userSettings();
}
