
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.Accessory;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IAccessoryPersistence extends IModelPersistence<Accessory> {
  public Accessory create(final Integer room_id, final String name, final String value, final Long created_at, final Long updated_at) throws IOException;
  public Set<Accessory> findByRoomId(Integer value)  throws IOException;
  public Set<Accessory> findByName(String value)  throws IOException;
  public Set<Accessory> findByValue(String value)  throws IOException;
  public Set<Accessory> findByCreatedAt(Long value)  throws IOException;
  public Set<Accessory> findByUpdatedAt(Long value)  throws IOException;
}
