
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.EventsRoom;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IEventsRoomPersistence extends IModelPersistence<EventsRoom> {
  public EventsRoom create(final int event_id, final int room_id) throws IOException;
  public Set<EventsRoom> findByEventId(int value)  throws IOException;
  public Set<EventsRoom> findByRoomId(int value)  throws IOException;
}
