
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.GroupsPerson;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IGroupsPersonPersistence extends IModelPersistence<GroupsPerson> {
  public GroupsPerson create(final int group_id, final int person_id) throws IOException;
  public Set<GroupsPerson> findByGroupId(int value)  throws IOException;
  public Set<GroupsPerson> findByPersonId(int value)  throws IOException;
}
