
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.Room;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IRoomPersistence extends IModelPersistence<Room> {
  public Room create(final String code, final String category, final Integer capacity, final Integer capacity_exam, final String description, final Long created_at, final Long updated_at) throws IOException;
  public Set<Room> findByCode(String value)  throws IOException;
  public Set<Room> findByCategory(String value)  throws IOException;
  public Set<Room> findByCapacity(Integer value)  throws IOException;
  public Set<Room> findByCapacityExam(Integer value)  throws IOException;
  public Set<Room> findByDescription(String value)  throws IOException;
  public Set<Room> findByCreatedAt(Long value)  throws IOException;
  public Set<Room> findByUpdatedAt(Long value)  throws IOException;
}
