
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.SchoolTerm;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface ISchoolTermPersistence extends IModelPersistence<SchoolTerm> {
  public SchoolTerm create(final String name, final Long start, final Long end, final Long created_at, final Long updated_at) throws IOException;
  public Set<SchoolTerm> findByName(String value)  throws IOException;
  public Set<SchoolTerm> findByStart(Long value)  throws IOException;
  public Set<SchoolTerm> findByEnd(Long value)  throws IOException;
  public Set<SchoolTerm> findByCreatedAt(Long value)  throws IOException;
  public Set<SchoolTerm> findByUpdatedAt(Long value)  throws IOException;
}
