
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.Subject;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface ISubjectPersistence extends IModelPersistence<Subject> {
  public Subject create(final Integer term_id, final Integer person_id, final Integer teacher_group_id, final Integer student_group_id, final String name, final String code, final String description, final Long created_at, final Long updated_at) throws IOException;
  public Set<Subject> findByTermId(Integer value)  throws IOException;
  public Set<Subject> findByPersonId(Integer value)  throws IOException;
  public Set<Subject> findByTeacherGroupId(Integer value)  throws IOException;
  public Set<Subject> findByStudentGroupId(Integer value)  throws IOException;
  public Set<Subject> findByName(String value)  throws IOException;
  public Set<Subject> findByCode(String value)  throws IOException;
  public Set<Subject> findByDescription(String value)  throws IOException;
  public Set<Subject> findByCreatedAt(Long value)  throws IOException;
  public Set<Subject> findByUpdatedAt(Long value)  throws IOException;
}
