
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.UserSetting;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IUserSettingPersistence extends IModelPersistence<UserSetting> {
  public UserSetting create(final Integer person_id, final String name, final String value, final Long created_at, final Long updated_at) throws IOException;
  public Set<UserSetting> findByPersonId(Integer value)  throws IOException;
  public Set<UserSetting> findByName(String value)  throws IOException;
  public Set<UserSetting> findByValue(String value)  throws IOException;
  public Set<UserSetting> findByCreatedAt(Long value)  throws IOException;
  public Set<UserSetting> findByUpdatedAt(Long value)  throws IOException;
}
