
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.mock_impl;

import java.util.Arrays;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractMockDatabaseModel;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.Accessory;
import javadb.timely.database_1.iface.IAccessoryPersistence;

import javadb.timely.IDatabases;

public class BaseMockAccessoryPersistenceImpl extends AbstractMockDatabaseModel<Accessory> implements IAccessoryPersistence {
  private final IDatabases databases;

  private static AtomicInteger curId = new AtomicInteger(1);

  public BaseMockAccessoryPersistenceImpl(IDatabases databases) {
    super();
    this.databases = databases;
  }

  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    Integer room_id = (Integer) fieldsMap.get(Accessory._Fields.room_id);
    String name = (String) fieldsMap.get(Accessory._Fields.name);
    String value = (String) fieldsMap.get(Accessory._Fields.value);
    Long created_at = (Long) fieldsMap.get(Accessory._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(Accessory._Fields.updated_at);
    return create(room_id, name, value, created_at, updated_at);
  }


  public Accessory create(final Integer room_id, final String name, final String value, final Long created_at, final Long updated_at) throws IOException {
    long __id = curId.getAndIncrement();
    Accessory newInst = new Accessory(__id, room_id, name, value, created_at, updated_at, databases);
    records.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<Accessory> find(Map<Enum, Object> fieldsMap) throws IOException {
    return super.realFind(fieldsMap);
  }

  public Set<Accessory> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    return super.realFind(ids, fieldsMap);
  }

  public Set<Accessory> findByRoomId(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Accessory._Fields.room_id, value);}});
  }

  public Set<Accessory> findByName(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Accessory._Fields.name, value);}});
  }

  public Set<Accessory> findByValue(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Accessory._Fields.value, value);}});
  }

  public Set<Accessory> findByCreatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Accessory._Fields.created_at, value);}});
  }

  public Set<Accessory> findByUpdatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Accessory._Fields.updated_at, value);}});
  }
}
