
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.mock_impl;

import java.util.Arrays;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractMockDatabaseModel;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.Group;
import javadb.timely.database_1.iface.IGroupPersistence;

import javadb.timely.IDatabases;

public class BaseMockGroupPersistenceImpl extends AbstractMockDatabaseModel<Group> implements IGroupPersistence {
  private final IDatabases databases;

  private static AtomicInteger curId = new AtomicInteger(1);

  public BaseMockGroupPersistenceImpl(IDatabases databases) {
    super();
    this.databases = databases;
  }


  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    String type = (String) fieldsMap.get(Group._Fields.type);
    String name = (String) fieldsMap.get(Group._Fields.name);
    Integer parent_id = (Integer) fieldsMap.get(Group._Fields.parent_id);
    Long created_at = (Long) fieldsMap.get(Group._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(Group._Fields.updated_at);
    return create(type, name, parent_id, created_at, updated_at);
  }


  public Group create(final String type, final String name, final Integer parent_id, final Long created_at, final Long updated_at) throws IOException {
    long __id = curId.getAndIncrement();
    Group newInst = new Group(__id, type, name, parent_id, created_at, updated_at, databases);
    records.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<Group> find(Map<Enum, Object> fieldsMap) throws IOException {
    return super.realFind(fieldsMap);
  }

  public Set<Group> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    return super.realFind(ids, fieldsMap);
  }

  public Set<Group> findByType(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.type, value);}});
  }

  public Set<Group> findByName(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.name, value);}});
  }

  public Set<Group> findByParentId(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.parent_id, value);}});
  }

  public Set<Group> findByCreatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.created_at, value);}});
  }

  public Set<Group> findByUpdatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.updated_at, value);}});
  }
}
