
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.mock_impl;

import java.util.Arrays;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractMockDatabaseModel;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.UserSetting;
import javadb.timely.database_1.iface.IUserSettingPersistence;

import javadb.timely.IDatabases;

public class BaseMockUserSettingPersistenceImpl extends AbstractMockDatabaseModel<UserSetting> implements IUserSettingPersistence {
  private final IDatabases databases;

  private static AtomicInteger curId = new AtomicInteger(1);

  public BaseMockUserSettingPersistenceImpl(IDatabases databases) {
    super();
    this.databases = databases;
  }

  @Override
  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    Integer person_id = (Integer) fieldsMap.get(UserSetting._Fields.person_id);
    String name = (String) fieldsMap.get(UserSetting._Fields.name);
    String value = (String) fieldsMap.get(UserSetting._Fields.value);
    Long created_at = (Long) fieldsMap.get(UserSetting._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(UserSetting._Fields.updated_at);
    return create(person_id, name, value, created_at, updated_at);
  }


  public UserSetting create(final Integer person_id, final String name, final String value, final Long created_at, final Long updated_at) throws IOException {
    long __id = curId.getAndIncrement();
    UserSetting newInst = new UserSetting(__id, person_id, name, value, created_at, updated_at, databases);
    records.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<UserSetting> find(Map<Enum, Object> fieldsMap) throws IOException {
    return super.realFind(fieldsMap);
  }

  public Set<UserSetting> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    return super.realFind(ids, fieldsMap);
  }

  public Set<UserSetting> findByPersonId(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(UserSetting._Fields.person_id, value);}});
  }

  public Set<UserSetting> findByName(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(UserSetting._Fields.name, value);}});
  }

  public Set<UserSetting> findByValue(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(UserSetting._Fields.value, value);}});
  }

  public Set<UserSetting> findByCreatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(UserSetting._Fields.created_at, value);}});
  }

  public Set<UserSetting> findByUpdatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(UserSetting._Fields.updated_at, value);}});
  }
}
