
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.impl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractDatabaseModel;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.Group;
import javadb.timely.database_1.iface.IGroupPersistence;

import javadb.timely.IDatabases;

public class BaseGroupPersistenceImpl extends AbstractDatabaseModel<Group> implements IGroupPersistence {
  private final IDatabases databases;

  public BaseGroupPersistenceImpl(BaseDatabaseConnection conn, IDatabases databases) {
    super(conn, "groups", Arrays.asList("type", "name", "parent_id", "created_at", "updated_at"));
    this.databases = databases;
  }

  @Override
  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    String type = (String) fieldsMap.get(Group._Fields.type);
    String name = (String) fieldsMap.get(Group._Fields.name);
    Integer parent_id = (Integer) fieldsMap.get(Group._Fields.parent_id);
    Long created_at = (Long) fieldsMap.get(Group._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(Group._Fields.updated_at);
    return create(type, name, parent_id, created_at, updated_at);
  }


  public Group create(final String type, final String name, final Integer parent_id, final Long created_at, final Long updated_at) throws IOException {
    long __id = realCreate(new AttrSetter() {
      public void set(PreparedStatement stmt) throws SQLException {
        if (type == null) {
          stmt.setNull(1, java.sql.Types.CHAR);
        } else {
          stmt.setString(1, type);
        }
        if (name == null) {
          stmt.setNull(2, java.sql.Types.CHAR);
        } else {
          stmt.setString(2, name);
        }
        if (parent_id == null) {
          stmt.setNull(3, java.sql.Types.INTEGER);
        } else {
          stmt.setInt(3, parent_id);
        }
        if (created_at == null) {
          stmt.setNull(4, java.sql.Types.DATE);
        } else {
          stmt.setTimestamp(4, new Timestamp(created_at));
        }
        if (updated_at == null) {
          stmt.setNull(5, java.sql.Types.DATE);
        } else {
          stmt.setTimestamp(5, new Timestamp(updated_at));
        }
      }
    }, getInsertStatement(Arrays.asList("type", "name", "parent_id", "created_at", "updated_at")));
    Group newInst = new Group(__id, type, name, parent_id, created_at, updated_at, databases);
    cachedById.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<Group> find(Map<Enum, Object> fieldsMap) throws IOException {
    return find(null, fieldsMap);
  }

  public Set<Group> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    Set<Group> foundSet = new HashSet<Group>();
    
    if (fieldsMap == null || fieldsMap.isEmpty()) {
      return foundSet;
    }

    StringBuilder statementString = new StringBuilder();
    statementString.append("SELECT * FROM groups WHERE (");
    List<Object> nonNullValues = new ArrayList<Object>();
    List<Group._Fields> nonNullValueFields = new ArrayList<Group._Fields>();

    Iterator<Map.Entry<Enum, Object>> iter = fieldsMap.entrySet().iterator();
    while (iter.hasNext()) {
      Map.Entry<Enum, Object> entry = iter.next();
      Enum field = entry.getKey();
      Object value = entry.getValue();
      
      String queryValue = value != null ? " = ? " : " IS NULL";
      if (value != null) {
        nonNullValueFields.add((Group._Fields) field);
        nonNullValues.add(value);
      }

      statementString.append(field + queryValue);
      if (iter.hasNext()) {
        statementString.append(" AND ");
      }
    }
    if (ids != null) statementString.append(" AND " + getIdSetCondition(ids));
    statementString.append(")");

    PreparedStatement preparedStatement = getPreparedStatement(statementString.toString());

    for (int i = 0; i < nonNullValues.size(); i++) {
      Group._Fields field = nonNullValueFields.get(i);
      try {
        switch (field) {
          case type:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case name:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case parent_id:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
          case created_at:
            preparedStatement.setTimestamp(i+1, new Timestamp((Long) nonNullValues.get(i)));
            break;
          case updated_at:
            preparedStatement.setTimestamp(i+1, new Timestamp((Long) nonNullValues.get(i)));
            break;
        }
      } catch (SQLException e) {
        throw new IOException(e);
      }
    }
    executeQuery(foundSet, preparedStatement);

    return foundSet;
  }

  @Override
  protected void setAttrs(Group model, PreparedStatement stmt) throws SQLException {
    if (model.getType() == null) {
      stmt.setNull(1, java.sql.Types.CHAR);
    } else {
      stmt.setString(1, model.getType());
    }
    if (model.getName() == null) {
      stmt.setNull(2, java.sql.Types.CHAR);
    } else {
      stmt.setString(2, model.getName());
    }
    if (model.getParentId() == null) {
      stmt.setNull(3, java.sql.Types.INTEGER);
    } else {
      stmt.setInt(3, model.getParentId());
    }
    if (model.getCreatedAt() == null) {
      stmt.setNull(4, java.sql.Types.DATE);
    } else {
      stmt.setTimestamp(4, new Timestamp(model.getCreatedAt()));
    }
    if (model.getUpdatedAt() == null) {
      stmt.setNull(5, java.sql.Types.DATE);
    } else {
      stmt.setTimestamp(5, new Timestamp(model.getUpdatedAt()));
    }
    stmt.setLong(6, model.getId());
  }

  @Override
  protected Group instanceFromResultSet(ResultSet rs) throws SQLException {
    return new Group(rs.getLong("id"),
      rs.getString("type"),
      rs.getString("name"),
      getIntOrNull(rs, "parent_id"),
      getDateAsLong(rs, "created_at"),
      getDateAsLong(rs, "updated_at"),
      databases
    );
  }

  public Set<Group> findByType(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.type, value);}});
  }

  public Set<Group> findByName(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.name, value);}});
  }

  public Set<Group> findByParentId(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.parent_id, value);}});
  }

  public Set<Group> findByCreatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.created_at, value);}});
  }

  public Set<Group> findByUpdatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Group._Fields.updated_at, value);}});
  }
}
