
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.impl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractDatabaseModel;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.EventsRoom;
import javadb.timely.database_1.iface.IEventsRoomPersistence;

import javadb.timely.IDatabases;

public class BaseEventsRoomPersistenceImpl extends AbstractDatabaseModel<EventsRoom> implements IEventsRoomPersistence {
  private final IDatabases databases;

  public BaseEventsRoomPersistenceImpl(BaseDatabaseConnection conn, IDatabases databases) {
    super(conn, "events_rooms", Arrays.asList("event_id", "room_id"));
    this.databases = databases;
  }

  @Override
  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    int event_id = (Integer) fieldsMap.get(EventsRoom._Fields.event_id);
    int room_id = (Integer) fieldsMap.get(EventsRoom._Fields.room_id);
    return create(event_id, room_id);
  }


  public EventsRoom create(final int event_id, final int room_id) throws IOException {
    long __id = realCreate(new AttrSetter() {
      public void set(PreparedStatement stmt) throws SQLException {
          stmt.setInt(1, event_id);
          stmt.setInt(2, room_id);
      }
    }, getInsertStatement(Arrays.asList("event_id", "room_id")));
    EventsRoom newInst = new EventsRoom(__id, event_id, room_id, databases);
    cachedById.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<EventsRoom> find(Map<Enum, Object> fieldsMap) throws IOException {
    return find(null, fieldsMap);
  }

  public Set<EventsRoom> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    Set<EventsRoom> foundSet = new HashSet<EventsRoom>();
    
    if (fieldsMap == null || fieldsMap.isEmpty()) {
      return foundSet;
    }

    StringBuilder statementString = new StringBuilder();
    statementString.append("SELECT * FROM events_rooms WHERE (");
    List<Object> nonNullValues = new ArrayList<Object>();
    List<EventsRoom._Fields> nonNullValueFields = new ArrayList<EventsRoom._Fields>();

    Iterator<Map.Entry<Enum, Object>> iter = fieldsMap.entrySet().iterator();
    while (iter.hasNext()) {
      Map.Entry<Enum, Object> entry = iter.next();
      Enum field = entry.getKey();
      Object value = entry.getValue();
      
      String queryValue = value != null ? " = ? " : " IS NULL";
      if (value != null) {
        nonNullValueFields.add((EventsRoom._Fields) field);
        nonNullValues.add(value);
      }

      statementString.append(field + queryValue);
      if (iter.hasNext()) {
        statementString.append(" AND ");
      }
    }
    if (ids != null) statementString.append(" AND " + getIdSetCondition(ids));
    statementString.append(")");

    PreparedStatement preparedStatement = getPreparedStatement(statementString.toString());

    for (int i = 0; i < nonNullValues.size(); i++) {
      EventsRoom._Fields field = nonNullValueFields.get(i);
      try {
        switch (field) {
          case event_id:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
          case room_id:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
        }
      } catch (SQLException e) {
        throw new IOException(e);
      }
    }
    executeQuery(foundSet, preparedStatement);

    return foundSet;
  }

  @Override
  protected void setAttrs(EventsRoom model, PreparedStatement stmt) throws SQLException {
    {
      stmt.setInt(1, model.getEventId());
    }
    {
      stmt.setInt(2, model.getRoomId());
    }
    stmt.setLong(3, model.getId());
  }

  @Override
  protected EventsRoom instanceFromResultSet(ResultSet rs) throws SQLException {
    return new EventsRoom(rs.getLong("id"),
      getIntOrNull(rs, "event_id"),
      getIntOrNull(rs, "room_id"),
      databases
    );
  }

  public Set<EventsRoom> findByEventId(final int value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(EventsRoom._Fields.event_id, value);}});
  }

  public Set<EventsRoom> findByRoomId(final int value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(EventsRoom._Fields.room_id, value);}});
  }
}
