
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.impl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractDatabaseModel;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.Room;
import javadb.timely.database_1.iface.IRoomPersistence;

import javadb.timely.IDatabases;

public class BaseRoomPersistenceImpl extends AbstractDatabaseModel<Room> implements IRoomPersistence {
  private final IDatabases databases;

  public BaseRoomPersistenceImpl(BaseDatabaseConnection conn, IDatabases databases) {
    super(conn, "rooms", Arrays.asList("code", "category", "capacity", "capacity_exam", "description", "created_at", "updated_at"));
    this.databases = databases;
  }

  @Override
  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    String code = (String) fieldsMap.get(Room._Fields.code);
    String category = (String) fieldsMap.get(Room._Fields.category);
    Integer capacity = (Integer) fieldsMap.get(Room._Fields.capacity);
    Integer capacity_exam = (Integer) fieldsMap.get(Room._Fields.capacity_exam);
    String description = (String) fieldsMap.get(Room._Fields.description);
    Long created_at = (Long) fieldsMap.get(Room._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(Room._Fields.updated_at);
    return create(code, category, capacity, capacity_exam, description, created_at, updated_at);
  }


  public Room create(final String code, final String category, final Integer capacity, final Integer capacity_exam, final String description, final Long created_at, final Long updated_at) throws IOException {
    long __id = realCreate(new AttrSetter() {
      public void set(PreparedStatement stmt) throws SQLException {
        if (code == null) {
          stmt.setNull(1, java.sql.Types.CHAR);
        } else {
          stmt.setString(1, code);
        }
        if (category == null) {
          stmt.setNull(2, java.sql.Types.CHAR);
        } else {
          stmt.setString(2, category);
        }
        if (capacity == null) {
          stmt.setNull(3, java.sql.Types.INTEGER);
        } else {
          stmt.setInt(3, capacity);
        }
        if (capacity_exam == null) {
          stmt.setNull(4, java.sql.Types.INTEGER);
        } else {
          stmt.setInt(4, capacity_exam);
        }
        if (description == null) {
          stmt.setNull(5, java.sql.Types.CHAR);
        } else {
          stmt.setString(5, description);
        }
        if (created_at == null) {
          stmt.setNull(6, java.sql.Types.DATE);
        } else {
          stmt.setTimestamp(6, new Timestamp(created_at));
        }
        if (updated_at == null) {
          stmt.setNull(7, java.sql.Types.DATE);
        } else {
          stmt.setTimestamp(7, new Timestamp(updated_at));
        }
      }
    }, getInsertStatement(Arrays.asList("code", "category", "capacity", "capacity_exam", "description", "created_at", "updated_at")));
    Room newInst = new Room(__id, code, category, capacity, capacity_exam, description, created_at, updated_at, databases);
    cachedById.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<Room> find(Map<Enum, Object> fieldsMap) throws IOException {
    return find(null, fieldsMap);
  }

  public Set<Room> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    Set<Room> foundSet = new HashSet<Room>();
    
    if (fieldsMap == null || fieldsMap.isEmpty()) {
      return foundSet;
    }

    StringBuilder statementString = new StringBuilder();
    statementString.append("SELECT * FROM rooms WHERE (");
    List<Object> nonNullValues = new ArrayList<Object>();
    List<Room._Fields> nonNullValueFields = new ArrayList<Room._Fields>();

    Iterator<Map.Entry<Enum, Object>> iter = fieldsMap.entrySet().iterator();
    while (iter.hasNext()) {
      Map.Entry<Enum, Object> entry = iter.next();
      Enum field = entry.getKey();
      Object value = entry.getValue();
      
      String queryValue = value != null ? " = ? " : " IS NULL";
      if (value != null) {
        nonNullValueFields.add((Room._Fields) field);
        nonNullValues.add(value);
      }

      statementString.append(field + queryValue);
      if (iter.hasNext()) {
        statementString.append(" AND ");
      }
    }
    if (ids != null) statementString.append(" AND " + getIdSetCondition(ids));
    statementString.append(")");

    PreparedStatement preparedStatement = getPreparedStatement(statementString.toString());

    for (int i = 0; i < nonNullValues.size(); i++) {
      Room._Fields field = nonNullValueFields.get(i);
      try {
        switch (field) {
          case code:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case category:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case capacity:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
          case capacity_exam:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
          case description:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case created_at:
            preparedStatement.setTimestamp(i+1, new Timestamp((Long) nonNullValues.get(i)));
            break;
          case updated_at:
            preparedStatement.setTimestamp(i+1, new Timestamp((Long) nonNullValues.get(i)));
            break;
        }
      } catch (SQLException e) {
        throw new IOException(e);
      }
    }
    executeQuery(foundSet, preparedStatement);

    return foundSet;
  }

  @Override
  protected void setAttrs(Room model, PreparedStatement stmt) throws SQLException {
    if (model.getCode() == null) {
      stmt.setNull(1, java.sql.Types.CHAR);
    } else {
      stmt.setString(1, model.getCode());
    }
    if (model.getCategory() == null) {
      stmt.setNull(2, java.sql.Types.CHAR);
    } else {
      stmt.setString(2, model.getCategory());
    }
    if (model.getCapacity() == null) {
      stmt.setNull(3, java.sql.Types.INTEGER);
    } else {
      stmt.setInt(3, model.getCapacity());
    }
    if (model.getCapacityExam() == null) {
      stmt.setNull(4, java.sql.Types.INTEGER);
    } else {
      stmt.setInt(4, model.getCapacityExam());
    }
    if (model.getDescription() == null) {
      stmt.setNull(5, java.sql.Types.CHAR);
    } else {
      stmt.setString(5, model.getDescription());
    }
    if (model.getCreatedAt() == null) {
      stmt.setNull(6, java.sql.Types.DATE);
    } else {
      stmt.setTimestamp(6, new Timestamp(model.getCreatedAt()));
    }
    if (model.getUpdatedAt() == null) {
      stmt.setNull(7, java.sql.Types.DATE);
    } else {
      stmt.setTimestamp(7, new Timestamp(model.getUpdatedAt()));
    }
    stmt.setLong(8, model.getId());
  }

  @Override
  protected Room instanceFromResultSet(ResultSet rs) throws SQLException {
    return new Room(rs.getLong("id"),
      rs.getString("code"),
      rs.getString("category"),
      getIntOrNull(rs, "capacity"),
      getIntOrNull(rs, "capacity_exam"),
      rs.getString("description"),
      getDateAsLong(rs, "created_at"),
      getDateAsLong(rs, "updated_at"),
      databases
    );
  }

  public Set<Room> findByCode(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.code, value);}});
  }

  public Set<Room> findByCategory(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.category, value);}});
  }

  public Set<Room> findByCapacity(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.capacity, value);}});
  }

  public Set<Room> findByCapacityExam(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.capacity_exam, value);}});
  }

  public Set<Room> findByDescription(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.description, value);}});
  }

  public Set<Room> findByCreatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.created_at, value);}});
  }

  public Set<Room> findByUpdatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(Room._Fields.updated_at, value);}});
  }
}
