
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.impl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractDatabaseModel;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.GroupsPerson;
import javadb.timely.database_1.iface.IGroupsPersonPersistence;

import javadb.timely.IDatabases;

public class BaseGroupsPersonPersistenceImpl extends AbstractDatabaseModel<GroupsPerson> implements IGroupsPersonPersistence {
  private final IDatabases databases;

  public BaseGroupsPersonPersistenceImpl(BaseDatabaseConnection conn, IDatabases databases) {
    super(conn, "groups_people", Arrays.asList("group_id", "person_id"));
    this.databases = databases;
  }

  @Override
  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    int group_id = (Integer) fieldsMap.get(GroupsPerson._Fields.group_id);
    int person_id = (Integer) fieldsMap.get(GroupsPerson._Fields.person_id);
    return create(group_id, person_id);
  }


  public GroupsPerson create(final int group_id, final int person_id) throws IOException {
    long __id = realCreate(new AttrSetter() {
      public void set(PreparedStatement stmt) throws SQLException {
          stmt.setInt(1, group_id);
          stmt.setInt(2, person_id);
      }
    }, getInsertStatement(Arrays.asList("group_id", "person_id")));
    GroupsPerson newInst = new GroupsPerson(__id, group_id, person_id, databases);
    cachedById.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<GroupsPerson> find(Map<Enum, Object> fieldsMap) throws IOException {
    return find(null, fieldsMap);
  }

  public Set<GroupsPerson> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    Set<GroupsPerson> foundSet = new HashSet<GroupsPerson>();
    
    if (fieldsMap == null || fieldsMap.isEmpty()) {
      return foundSet;
    }

    StringBuilder statementString = new StringBuilder();
    statementString.append("SELECT * FROM groups_people WHERE (");
    List<Object> nonNullValues = new ArrayList<Object>();
    List<GroupsPerson._Fields> nonNullValueFields = new ArrayList<GroupsPerson._Fields>();

    Iterator<Map.Entry<Enum, Object>> iter = fieldsMap.entrySet().iterator();
    while (iter.hasNext()) {
      Map.Entry<Enum, Object> entry = iter.next();
      Enum field = entry.getKey();
      Object value = entry.getValue();
      
      String queryValue = value != null ? " = ? " : " IS NULL";
      if (value != null) {
        nonNullValueFields.add((GroupsPerson._Fields) field);
        nonNullValues.add(value);
      }

      statementString.append(field + queryValue);
      if (iter.hasNext()) {
        statementString.append(" AND ");
      }
    }
    if (ids != null) statementString.append(" AND " + getIdSetCondition(ids));
    statementString.append(")");

    PreparedStatement preparedStatement = getPreparedStatement(statementString.toString());

    for (int i = 0; i < nonNullValues.size(); i++) {
      GroupsPerson._Fields field = nonNullValueFields.get(i);
      try {
        switch (field) {
          case group_id:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
          case person_id:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
        }
      } catch (SQLException e) {
        throw new IOException(e);
      }
    }
    executeQuery(foundSet, preparedStatement);

    return foundSet;
  }

  @Override
  protected void setAttrs(GroupsPerson model, PreparedStatement stmt) throws SQLException {
    {
      stmt.setInt(1, model.getGroupId());
    }
    {
      stmt.setInt(2, model.getPersonId());
    }
    stmt.setLong(3, model.getId());
  }

  @Override
  protected GroupsPerson instanceFromResultSet(ResultSet rs) throws SQLException {
    return new GroupsPerson(rs.getLong("id"),
      getIntOrNull(rs, "group_id"),
      getIntOrNull(rs, "person_id"),
      databases
    );
  }

  public Set<GroupsPerson> findByGroupId(final int value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(GroupsPerson._Fields.group_id, value);}});
  }

  public Set<GroupsPerson> findByPersonId(final int value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(GroupsPerson._Fields.person_id, value);}});
  }
}
