
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.models;

import java.io.IOException;
import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

import javadb.timely.database_1.IDatabase1;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;

import javadb.timely.IDatabases;

public class EventsRoom extends ModelWithId {
  // Fields
  private int __event_id;
  private int __room_id;

  // Associations

  public enum _Fields {
    event_id,
    room_id,
  }

  public EventsRoom(long id, final int event_id, final int room_id, IDatabases databases) {
    super(id);
    this.__event_id = event_id;
    this.__room_id = room_id;
  }

  public EventsRoom(long id, final int event_id, final int room_id) {
    super(id);
    this.__event_id = event_id;
    this.__room_id = room_id;
  }

  public EventsRoom(long id, Map<Enum, Object> fieldsMap) {
    super(id);
    int event_id = (Integer) fieldsMap.get(EventsRoom._Fields.event_id);
    int room_id = (Integer) fieldsMap.get(EventsRoom._Fields.room_id);
    this.__event_id = event_id;
    this.__room_id = room_id;
  }

  public EventsRoom (EventsRoom other) {
    super(other.getId());
    this.__event_id = other.getEventId();
    this.__room_id = other.getRoomId();
  }

  public int getEventId(){
    return __event_id;
  }

  public void setEventId(int newval){
    this.__event_id = newval;
    cachedHashCode = 0;
  }

  public int getRoomId(){
    return __room_id;
  }

  public void setRoomId(int newval){
    this.__room_id = newval;
    cachedHashCode = 0;
  }

  public void setField(_Fields field, Object value) {
    switch (field) {
      case event_id:
        setEventId((Integer) value);
        break;
      case room_id:
        setRoomId((Integer) value);
        break;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(_Fields field) {
    switch (field) {
      case event_id:
        return int.class;
      case room_id:
        return int.class;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(String fieldName) {    
    if (fieldName.equals("event_id")) {
      return int.class;
    }
    if (fieldName.equals("room_id")) {
      return int.class;
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  @Override
  public Object getField(String fieldName) {
    if (fieldName.equals("id")) {
      return getId();
    }
    if (fieldName.equals("event_id")) {
      return getEventId();
    }
    if (fieldName.equals("room_id")) {
      return getRoomId();
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Object getField(_Fields field) {
    switch (field) {
      case event_id:
        return getEventId();
      case room_id:
        return getRoomId();
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  public static Object getDefaultValue(_Fields field) {
    switch (field) {
      case event_id:
        return null;
      case room_id:
        return null;
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  @Override
  public Set<Enum> getFieldSet() {
    Set set = EnumSet.allOf(_Fields.class);
    return set;
  }

  @Override
  public ModelWithId getCopy() {
    return new EventsRoom(this);
  }

  public String toString() {
    return "<EventsRoom"
      + " event_id: " + __event_id
      + " room_id: " + __room_id
      + ">";
  }
}
