
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.models;

import java.io.IOException;
import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

import javadb.timely.database_1.IDatabase1;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;

import javadb.timely.IDatabases;

public class Group extends ModelWithId {
  // Fields
  private String __type;
  private String __name;
  private Integer __parent_id;
  private Long __created_at;
  private Long __updated_at;

  // Associations
  private HasManyAssociation<Event> __assoc_events;

  public enum _Fields {
    type,
    name,
    parent_id,
    created_at,
    updated_at,
  }

  public Group(long id, final String type, final String name, final Integer parent_id, final Long created_at, final Long updated_at, IDatabases databases) {
    super(id);
    this.__type = type;
    this.__name = name;
    this.__parent_id = parent_id;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
    this.__assoc_events = new HasManyAssociation<Event>(databases.getDatabase1().events(), "group_id", id);
  }

  public Group(long id, final String type, final String name, final Integer parent_id, final Long created_at, final Long updated_at) {
    super(id);
    this.__type = type;
    this.__name = name;
    this.__parent_id = parent_id;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
  }

  public Group(long id, Map<Enum, Object> fieldsMap) {
    super(id);
    String type = (String) fieldsMap.get(Group._Fields.type);
    String name = (String) fieldsMap.get(Group._Fields.name);
    Integer parent_id = (Integer) fieldsMap.get(Group._Fields.parent_id);
    Long created_at = (Long) fieldsMap.get(Group._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(Group._Fields.updated_at);
    this.__type = type;
    this.__name = name;
    this.__parent_id = parent_id;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
  }

  public Group (Group other) {
    super(other.getId());
    this.__type = other.getType();
    this.__name = other.getName();
    this.__parent_id = other.getParentId();
    this.__created_at = other.getCreatedAt();
    this.__updated_at = other.getUpdatedAt();
  }

  public String getType(){
    return __type;
  }

  public void setType(String newval){
    this.__type = newval;
    cachedHashCode = 0;
  }

  public String getName(){
    return __name;
  }

  public void setName(String newval){
    this.__name = newval;
    cachedHashCode = 0;
  }

  public Integer getParentId(){
    return __parent_id;
  }

  public void setParentId(Integer newval){
    this.__parent_id = newval;
    cachedHashCode = 0;
  }

  public Long getCreatedAt(){
    return __created_at;
  }

  public void setCreatedAt(Long newval){
    this.__created_at = newval;
    cachedHashCode = 0;
  }

  public Long getUpdatedAt(){
    return __updated_at;
  }

  public void setUpdatedAt(Long newval){
    this.__updated_at = newval;
    cachedHashCode = 0;
  }

  public void setField(_Fields field, Object value) {
    switch (field) {
      case type:
        setType((String) value);
        break;
      case name:
        setName((String) value);
        break;
      case parent_id:
        setParentId((Integer) value);
        break;
      case created_at:
        setCreatedAt((Long) value);
        break;
      case updated_at:
        setUpdatedAt((Long) value);
        break;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(_Fields field) {
    switch (field) {
      case type:
        return String.class;
      case name:
        return String.class;
      case parent_id:
        return Integer.class;
      case created_at:
        return Long.class;
      case updated_at:
        return Long.class;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(String fieldName) {    
    if (fieldName.equals("type")) {
      return String.class;
    }
    if (fieldName.equals("name")) {
      return String.class;
    }
    if (fieldName.equals("parent_id")) {
      return Integer.class;
    }
    if (fieldName.equals("created_at")) {
      return Long.class;
    }
    if (fieldName.equals("updated_at")) {
      return Long.class;
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Set<Event> getEvents() throws IOException {
    return __assoc_events.get();
  }

  @Override
  public Object getField(String fieldName) {
    if (fieldName.equals("id")) {
      return getId();
    }
    if (fieldName.equals("type")) {
      return getType();
    }
    if (fieldName.equals("name")) {
      return getName();
    }
    if (fieldName.equals("parent_id")) {
      return getParentId();
    }
    if (fieldName.equals("created_at")) {
      return getCreatedAt();
    }
    if (fieldName.equals("updated_at")) {
      return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Object getField(_Fields field) {
    switch (field) {
      case type:
        return getType();
      case name:
        return getName();
      case parent_id:
        return getParentId();
      case created_at:
        return getCreatedAt();
      case updated_at:
        return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  public static Object getDefaultValue(_Fields field) {
    switch (field) {
      case type:
        return null;
      case name:
        return null;
      case parent_id:
        return null;
      case created_at:
        return null;
      case updated_at:
        return null;
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  @Override
  public Set<Enum> getFieldSet() {
    Set set = EnumSet.allOf(_Fields.class);
    return set;
  }

  @Override
  public ModelWithId getCopy() {
    return new Group(this);
  }

  public String toString() {
    return "<Group"
      + " type: " + __type
      + " name: " + __name
      + " parent_id: " + __parent_id
      + " created_at: " + __created_at
      + " updated_at: " + __updated_at
      + ">";
  }
}
