
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.models;

import java.io.IOException;
import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

import javadb.timely.database_1.IDatabase1;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;

import javadb.timely.IDatabases;

public class SchoolTerm extends ModelWithId {
  // Fields
  private String __name;
  private Long __start;
  private Long __end;
  private Long __created_at;
  private Long __updated_at;

  // Associations
  private HasManyAssociation<TermSetting> __assoc_term_settings;

  public enum _Fields {
    name,
    start,
    end,
    created_at,
    updated_at,
  }

  public SchoolTerm(long id, final String name, final Long start, final Long end, final Long created_at, final Long updated_at, IDatabases databases) {
    super(id);
    this.__name = name;
    this.__start = start;
    this.__end = end;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
    this.__assoc_term_settings = new HasManyAssociation<TermSetting>(databases.getDatabase1().termSettings(), "school_term_id", id);
  }

  public SchoolTerm(long id, final String name, final Long start, final Long end, final Long created_at, final Long updated_at) {
    super(id);
    this.__name = name;
    this.__start = start;
    this.__end = end;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
  }

  public SchoolTerm(long id, Map<Enum, Object> fieldsMap) {
    super(id);
    String name = (String) fieldsMap.get(SchoolTerm._Fields.name);
    Long start = (Long) fieldsMap.get(SchoolTerm._Fields.start);
    Long end = (Long) fieldsMap.get(SchoolTerm._Fields.end);
    Long created_at = (Long) fieldsMap.get(SchoolTerm._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(SchoolTerm._Fields.updated_at);
    this.__name = name;
    this.__start = start;
    this.__end = end;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
  }

  public SchoolTerm (SchoolTerm other) {
    super(other.getId());
    this.__name = other.getName();
    this.__start = other.getStart();
    this.__end = other.getEnd();
    this.__created_at = other.getCreatedAt();
    this.__updated_at = other.getUpdatedAt();
  }

  public String getName(){
    return __name;
  }

  public void setName(String newval){
    this.__name = newval;
    cachedHashCode = 0;
  }

  public Long getStart(){
    return __start;
  }

  public void setStart(Long newval){
    this.__start = newval;
    cachedHashCode = 0;
  }

  public Long getEnd(){
    return __end;
  }

  public void setEnd(Long newval){
    this.__end = newval;
    cachedHashCode = 0;
  }

  public Long getCreatedAt(){
    return __created_at;
  }

  public void setCreatedAt(Long newval){
    this.__created_at = newval;
    cachedHashCode = 0;
  }

  public Long getUpdatedAt(){
    return __updated_at;
  }

  public void setUpdatedAt(Long newval){
    this.__updated_at = newval;
    cachedHashCode = 0;
  }

  public void setField(_Fields field, Object value) {
    switch (field) {
      case name:
        setName((String) value);
        break;
      case start:
        setStart((Long) value);
        break;
      case end:
        setEnd((Long) value);
        break;
      case created_at:
        setCreatedAt((Long) value);
        break;
      case updated_at:
        setUpdatedAt((Long) value);
        break;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(_Fields field) {
    switch (field) {
      case name:
        return String.class;
      case start:
        return Long.class;
      case end:
        return Long.class;
      case created_at:
        return Long.class;
      case updated_at:
        return Long.class;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(String fieldName) {    
    if (fieldName.equals("name")) {
      return String.class;
    }
    if (fieldName.equals("start")) {
      return Long.class;
    }
    if (fieldName.equals("end")) {
      return Long.class;
    }
    if (fieldName.equals("created_at")) {
      return Long.class;
    }
    if (fieldName.equals("updated_at")) {
      return Long.class;
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Set<TermSetting> getTermSettings() throws IOException {
    return __assoc_term_settings.get();
  }

  @Override
  public Object getField(String fieldName) {
    if (fieldName.equals("id")) {
      return getId();
    }
    if (fieldName.equals("name")) {
      return getName();
    }
    if (fieldName.equals("start")) {
      return getStart();
    }
    if (fieldName.equals("end")) {
      return getEnd();
    }
    if (fieldName.equals("created_at")) {
      return getCreatedAt();
    }
    if (fieldName.equals("updated_at")) {
      return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Object getField(_Fields field) {
    switch (field) {
      case name:
        return getName();
      case start:
        return getStart();
      case end:
        return getEnd();
      case created_at:
        return getCreatedAt();
      case updated_at:
        return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  public static Object getDefaultValue(_Fields field) {
    switch (field) {
      case name:
        return null;
      case start:
        return null;
      case end:
        return null;
      case created_at:
        return null;
      case updated_at:
        return null;
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  @Override
  public Set<Enum> getFieldSet() {
    Set set = EnumSet.allOf(_Fields.class);
    return set;
  }

  @Override
  public ModelWithId getCopy() {
    return new SchoolTerm(this);
  }

  public String toString() {
    return "<SchoolTerm"
      + " name: " + __name
      + " start: " + __start
      + " end: " + __end
      + " created_at: " + __created_at
      + " updated_at: " + __updated_at
      + ">";
  }
}
