
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.models;

import java.io.IOException;
import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

import javadb.timely.database_1.IDatabase1;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;

import javadb.timely.IDatabases;

public class UserSetting extends ModelWithId {
  // Fields
  private Integer __person_id;
  private String __name;
  private String __value;
  private Long __created_at;
  private Long __updated_at;

  // Associations
  private BelongsToAssociation<Person> __assoc_person;

  public enum _Fields {
    person_id,
    name,
    value,
    created_at,
    updated_at,
  }

  public UserSetting(long id, final Integer person_id, final String name, final String value, final Long created_at, final Long updated_at, IDatabases databases) {
    super(id);
    this.__person_id = person_id;
    this.__name = name;
    this.__value = value;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
    this.__assoc_person = new BelongsToAssociation<Person>(databases.getDatabase1().people(), person_id == null ? null : person_id.longValue());
  }

  public UserSetting(long id, final Integer person_id, final String name, final String value, final Long created_at, final Long updated_at) {
    super(id);
    this.__person_id = person_id;
    this.__name = name;
    this.__value = value;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
  }

  public UserSetting(long id, Map<Enum, Object> fieldsMap) {
    super(id);
    Integer person_id = (Integer) fieldsMap.get(UserSetting._Fields.person_id);
    String name = (String) fieldsMap.get(UserSetting._Fields.name);
    String value = (String) fieldsMap.get(UserSetting._Fields.value);
    Long created_at = (Long) fieldsMap.get(UserSetting._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(UserSetting._Fields.updated_at);
    this.__person_id = person_id;
    this.__name = name;
    this.__value = value;
    this.__created_at = created_at;
    this.__updated_at = updated_at;
  }

  public UserSetting (UserSetting other) {
    super(other.getId());
    this.__person_id = other.getPersonId();
    this.__name = other.getName();
    this.__value = other.getValue();
    this.__created_at = other.getCreatedAt();
    this.__updated_at = other.getUpdatedAt();
  }

  public Integer getPersonId(){
    return __person_id;
  }

  public void setPersonId(Integer newval){
    this.__person_id = newval;
    cachedHashCode = 0;
  }

  public String getName(){
    return __name;
  }

  public void setName(String newval){
    this.__name = newval;
    cachedHashCode = 0;
  }

  public String getValue(){
    return __value;
  }

  public void setValue(String newval){
    this.__value = newval;
    cachedHashCode = 0;
  }

  public Long getCreatedAt(){
    return __created_at;
  }

  public void setCreatedAt(Long newval){
    this.__created_at = newval;
    cachedHashCode = 0;
  }

  public Long getUpdatedAt(){
    return __updated_at;
  }

  public void setUpdatedAt(Long newval){
    this.__updated_at = newval;
    cachedHashCode = 0;
  }

  public void setField(_Fields field, Object value) {
    switch (field) {
      case person_id:
        setPersonId((Integer) value);
        break;
      case name:
        setName((String) value);
        break;
      case value:
        setValue((String) value);
        break;
      case created_at:
        setCreatedAt((Long) value);
        break;
      case updated_at:
        setUpdatedAt((Long) value);
        break;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(_Fields field) {
    switch (field) {
      case person_id:
        return Integer.class;
      case name:
        return String.class;
      case value:
        return String.class;
      case created_at:
        return Long.class;
      case updated_at:
        return Long.class;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(String fieldName) {    
    if (fieldName.equals("person_id")) {
      return Integer.class;
    }
    if (fieldName.equals("name")) {
      return String.class;
    }
    if (fieldName.equals("value")) {
      return String.class;
    }
    if (fieldName.equals("created_at")) {
      return Long.class;
    }
    if (fieldName.equals("updated_at")) {
      return Long.class;
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Person getPerson() throws IOException {
    return __assoc_person.get();
  }

  @Override
  public Object getField(String fieldName) {
    if (fieldName.equals("id")) {
      return getId();
    }
    if (fieldName.equals("person_id")) {
      return getPersonId();
    }
    if (fieldName.equals("name")) {
      return getName();
    }
    if (fieldName.equals("value")) {
      return getValue();
    }
    if (fieldName.equals("created_at")) {
      return getCreatedAt();
    }
    if (fieldName.equals("updated_at")) {
      return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Object getField(_Fields field) {
    switch (field) {
      case person_id:
        return getPersonId();
      case name:
        return getName();
      case value:
        return getValue();
      case created_at:
        return getCreatedAt();
      case updated_at:
        return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  public static Object getDefaultValue(_Fields field) {
    switch (field) {
      case person_id:
        return null;
      case name:
        return null;
      case value:
        return null;
      case created_at:
        return null;
      case updated_at:
        return null;
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  @Override
  public Set<Enum> getFieldSet() {
    Set set = EnumSet.allOf(_Fields.class);
    return set;
  }

  @Override
  public ModelWithId getCopy() {
    return new UserSetting(this);
  }

  public String toString() {
    return "<UserSetting"
      + " person_id: " + __person_id
      + " name: " + __name
      + " value: " + __value
      + " created_at: " + __created_at
      + " updated_at: " + __updated_at
      + ">";
  }
}
