
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.impl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Timestamp;

import com.rapleaf.jack.AbstractDatabaseModel;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.rapleaf.jack.ModelWithId;

import javadb.timely.database_1.models.TermSetting;
import javadb.timely.database_1.iface.ITermSettingPersistence;

import javadb.timely.IDatabases;

public class BaseTermSettingPersistenceImpl extends AbstractDatabaseModel<TermSetting> implements ITermSettingPersistence {
  private final IDatabases databases;

  public BaseTermSettingPersistenceImpl(BaseDatabaseConnection conn, IDatabases databases) {
    super(conn, "term_settings", Arrays.asList("term_id", "name", "value", "created_at", "updated_at"));
    this.databases = databases;
  }

  @Override
  public ModelWithId create(Map<Enum, Object> fieldsMap) throws IOException {
    Integer term_id = (Integer) fieldsMap.get(TermSetting._Fields.term_id);
    String name = (String) fieldsMap.get(TermSetting._Fields.name);
    String value = (String) fieldsMap.get(TermSetting._Fields.value);
    Long created_at = (Long) fieldsMap.get(TermSetting._Fields.created_at);
    Long updated_at = (Long) fieldsMap.get(TermSetting._Fields.updated_at);
    return create(term_id, name, value, created_at, updated_at);
  }


  public TermSetting create(final Integer term_id, final String name, final String value, final Long created_at, final Long updated_at) throws IOException {
    long __id = realCreate(new AttrSetter() {
      public void set(PreparedStatement stmt) throws SQLException {
        if (term_id == null) {
          stmt.setNull(1, java.sql.Types.INTEGER);
        } else {
          stmt.setInt(1, term_id);
        }
        if (name == null) {
          stmt.setNull(2, java.sql.Types.CHAR);
        } else {
          stmt.setString(2, name);
        }
        if (value == null) {
          stmt.setNull(3, java.sql.Types.CHAR);
        } else {
          stmt.setString(3, value);
        }
        if (created_at == null) {
          stmt.setNull(4, java.sql.Types.DATE);
        } else {
          stmt.setTimestamp(4, new Timestamp(created_at));
        }
        if (updated_at == null) {
          stmt.setNull(5, java.sql.Types.DATE);
        } else {
          stmt.setTimestamp(5, new Timestamp(updated_at));
        }
      }
    }, getInsertStatement(Arrays.asList("term_id", "name", "value", "created_at", "updated_at")));
    TermSetting newInst = new TermSetting(__id, term_id, name, value, created_at, updated_at, databases);
    cachedById.put(__id, newInst);
    clearForeignKeyCache();
    return newInst;
  }


  public Set<TermSetting> find(Map<Enum, Object> fieldsMap) throws IOException {
    return find(null, fieldsMap);
  }

  public Set<TermSetting> find(Set<Long> ids, Map<Enum, Object> fieldsMap) throws IOException {
    Set<TermSetting> foundSet = new HashSet<TermSetting>();
    
    if (fieldsMap == null || fieldsMap.isEmpty()) {
      return foundSet;
    }

    StringBuilder statementString = new StringBuilder();
    statementString.append("SELECT * FROM term_settings WHERE (");
    List<Object> nonNullValues = new ArrayList<Object>();
    List<TermSetting._Fields> nonNullValueFields = new ArrayList<TermSetting._Fields>();

    Iterator<Map.Entry<Enum, Object>> iter = fieldsMap.entrySet().iterator();
    while (iter.hasNext()) {
      Map.Entry<Enum, Object> entry = iter.next();
      Enum field = entry.getKey();
      Object value = entry.getValue();
      
      String queryValue = value != null ? " = ? " : " IS NULL";
      if (value != null) {
        nonNullValueFields.add((TermSetting._Fields) field);
        nonNullValues.add(value);
      }

      statementString.append(field + queryValue);
      if (iter.hasNext()) {
        statementString.append(" AND ");
      }
    }
    if (ids != null) statementString.append(" AND " + getIdSetCondition(ids));
    statementString.append(")");

    PreparedStatement preparedStatement = getPreparedStatement(statementString.toString());

    for (int i = 0; i < nonNullValues.size(); i++) {
      TermSetting._Fields field = nonNullValueFields.get(i);
      try {
        switch (field) {
          case term_id:
            preparedStatement.setInt(i+1, (Integer) nonNullValues.get(i));
            break;
          case name:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case value:
            preparedStatement.setString(i+1, (String) nonNullValues.get(i));
            break;
          case created_at:
            preparedStatement.setTimestamp(i+1, new Timestamp((Long) nonNullValues.get(i)));
            break;
          case updated_at:
            preparedStatement.setTimestamp(i+1, new Timestamp((Long) nonNullValues.get(i)));
            break;
        }
      } catch (SQLException e) {
        throw new IOException(e);
      }
    }
    executeQuery(foundSet, preparedStatement);

    return foundSet;
  }

  @Override
  protected void setAttrs(TermSetting model, PreparedStatement stmt) throws SQLException {
    if (model.getTermId() == null) {
      stmt.setNull(1, java.sql.Types.INTEGER);
    } else {
      stmt.setInt(1, model.getTermId());
    }
    if (model.getName() == null) {
      stmt.setNull(2, java.sql.Types.CHAR);
    } else {
      stmt.setString(2, model.getName());
    }
    if (model.getValue() == null) {
      stmt.setNull(3, java.sql.Types.CHAR);
    } else {
      stmt.setString(3, model.getValue());
    }
    if (model.getCreatedAt() == null) {
      stmt.setNull(4, java.sql.Types.DATE);
    } else {
      stmt.setTimestamp(4, new Timestamp(model.getCreatedAt()));
    }
    if (model.getUpdatedAt() == null) {
      stmt.setNull(5, java.sql.Types.DATE);
    } else {
      stmt.setTimestamp(5, new Timestamp(model.getUpdatedAt()));
    }
    stmt.setLong(6, model.getId());
  }

  @Override
  protected TermSetting instanceFromResultSet(ResultSet rs) throws SQLException {
    return new TermSetting(rs.getLong("id"),
      getIntOrNull(rs, "term_id"),
      rs.getString("name"),
      rs.getString("value"),
      getDateAsLong(rs, "created_at"),
      getDateAsLong(rs, "updated_at"),
      databases
    );
  }

  public Set<TermSetting> findByTermId(final Integer value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(TermSetting._Fields.term_id, value);}});
  }

  public Set<TermSetting> findByName(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(TermSetting._Fields.name, value);}});
  }

  public Set<TermSetting> findByValue(final String value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(TermSetting._Fields.value, value);}});
  }

  public Set<TermSetting> findByCreatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(TermSetting._Fields.created_at, value);}});
  }

  public Set<TermSetting> findByUpdatedAt(final Long value) throws IOException {
    return find(new HashMap<Enum, Object>(){{put(TermSetting._Fields.updated_at, value);}});
  }
}
