databases_namespace: com.rapleaf.jack.test_project
databases:
  -
    root_namespace: com.rapleaf.jack.test_project.db

        # What do you want to call this database? Leave out the "_production".
        db_name: TimelyJava
        # The path to the schema.rb in your Rails project.
        schema_rb: schema.rb
        # The path to the app/models dir in your Rails project.
        models: models
