
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20111112181520 */
package javadb.timely.database_1.iface;

import javadb.timely.database_1.models.Group;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IGroupPersistence extends IModelPersistence<Group> {
  public Group create(final String type, final String name, final Integer parent_id, final Long created_at, final Long updated_at) throws IOException;
  public Set<Group> findByType(String value)  throws IOException;
  public Set<Group> findByName(String value)  throws IOException;
  public Set<Group> findByParentId(Integer value)  throws IOException;
  public Set<Group> findByCreatedAt(Long value)  throws IOException;
  public Set<Group> findByUpdatedAt(Long value)  throws IOException;
}
